name: vedic_astrology
description: Vedic astrology frontend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.0
  fl_chart: ^0.63.0
  provider: ^6.0.5
  http: ^1.1.0
  flutter_typeahead: ^5.2.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  time_picker_with_timezone: ^0.0.2
  touchable: ^1.0.0
  gpt_markdown: ^0.1.0
  pdf: ^3.10.4
  printing: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0

flutter:
  uses-material-design: true