name: vedic_astrology
description: Vedic astrology frontend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.0           # HTTP client
  fl_chart: ^0.63.0     # Charts for strengths
  provider: ^6.0.5      # State management
  intl: ^0.18.1         # Date formatting

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true